### ISSUE TITLE
Issue converting an Azure "Text to speech call" response to stream and loading it to an Azure Blob

### ISSUE THREAD

**Issue by dgoyal1504** [Azure-Samples/storage-blob-upload-from-webapp-node-v10#11]
> Please provide us with the following information:
> ---------------------------------------------------------------
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Update settings.js with 
      a. Cognitive (text to speech) subscription key, region and endpoint details
      b. Storage account key and other details
   2. Text to be converted as well the Blob file name are hard-coded in this test code. 

### Any log messages given by the failure
>Failure RestError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Verb</h2>
<hr><p>HTTP Error 400. The request verb is invalid.</p>
</BODY></HTML>

    at new RestError (c:\dkg\myCode\tts\node_modules\@azure\core-http\dist\index.js:2237:28)
    at c:\dkg\myCode\tts\node_modules\@azure\core-http\dist\index.js:3030:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Expected/desired behavior
> Console log should show "Success" and "I am done" 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 Home 1909 OS Build 18363.1016
### Versions
> Node version v12.18.3
package.json is enclosed. 
[ttsSample.zip](https://github.com/Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs/files/5195960/ttsSample.zip)
[ttsSample.zip](https://github.com/Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs/files/5195963/ttsSample.zip)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zzhxiaofeng** [comment]
Can you have a try to do this operation with [text to speech SDK](https://github.com/microsoft/cognitive-services-speech-sdk-js)?

**Comment by dgoyal1504** [comment]
> Can you have a try to do this operation with [text to speech SDK](https://github.com/microsoft/cognitive-services-speech-sdk-js)?

Thank you. I was able to resolve it yesterday by using the Node.js API for Blobl storage ...
