### ISSUE TITLE
Docs links broken

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure-Samples/storage-blob-upload-from-webapp-node-v10#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
![image](https://user-images.githubusercontent.com/10452642/122487775-e211f500-cf90-11eb-8f2f-41924481735d.png)
Links broken at https://docs.microsoft.com/en-us/samples/azure-samples/storage-blob-upload-from-webapp-node-v10/azure-storage-blob-upload-from-a-nodejs-web-application-using-the-v12-sdk/?source=docs

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by HarshaNalluru** [comment]
@jeremymeng @emmazhu @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Thanks for reporting @HarshaNalluru 

@jongio Looks like the samples at docs.microsoft/samples has not been updated in a while. The broken links are not present in this repo anymore.

**Comment by jongio** [comment]
@v-xuto - Can you please have a look?

**Comment by v-xuto** [comment]
@jongio - It may be wrong to open this issue under this repo. The repo corresponding to the [doc](https://docs.microsoft.com/en-us/samples/azure-samples/storage-blob-upload-from-webapp-node-v10/azure-storage-blob-upload-from-a-nodejs-web-application-using-the-v12-sdk/?source=docs) with the broken link is https://github.com/Azure-Samples/storage-blob-upload-from-webapp-node-v12. But the current repo is https://github.com/Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs. The README.md of these two repo is a bit similar, but there are some differences. Besides, I can't open the repo(https://github.com/Azure-Samples/storage-blob-upload-from-webapp-node-v12), I wonder if I don't have permission or this repo has been disabled.

**Comment by jongio** [comment]
The new locations are here: https://github.com/Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs

Please update links to point the corresponding subfolder.  Thanks

**Comment by v-xuto** [comment]
@jongio - Could you provide me the repo link which corresponding to this [doc](https://docs.microsoft.com/en-us/samples/azure-samples/storage-blob-upload-from-webapp-node-v10/azure-storage-blob-upload-from-a-nodejs-web-application-using-the-v12-sdk/?source=docs) ? Also if it's a private one, please give me the access permission.

**Comment by jongio** [comment]
It should be the link in my comment above

**Comment by v-xuto** [comment]
@HarshaNalluru The current issue should not exist anymore. The interface of the current document is shown in the figure below. Do you still have doubts? If not, we will close this issue.

[Docs link](https://docs.microsoft.com/en-us/samples/azure-samples/azure-sdk-for-js-storage-blob-stream-nodejs/stream-blobs-nodejs/):
![image](https://user-images.githubusercontent.com/57166602/146518143-10bef423-a25b-4fbd-8bef-67874dbd1c1c.png)

**Comment by HarshaNalluru** [comment]
🙂
